encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.get_title, name="get_title"),
    path("search", views.search, name="search"),
    path("add", views.newPage, name="newPage"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from markdown2 import Markdown
from django import forms
from django.urls import reverse
from random import choice

 
from . import util

class NewPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control mb-3', 'placeholder' : 'Example: CSS'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control mb-3', 'placeholder' : 'Example: CSS is a language that can be used to add style to an HTML page.'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def get_title(request, title):
    markdowner = Markdown()
    entry = util.get_entry(title)
    if entry is None:
        return render(request, "encyclopedia/404.html", {
            "entriesTitle": title
        })
    else:
        return render(request, "encyclopedia/entries.html", {
            "entries": markdowner.convert(entry),
            "entriesTitle": title
        })

def search(request):
    data = request.GET.get('q','')
    if (util.get_entry(data) is None):
        stringEntries = []
        for entries in util.list_entries():
            if data.upper() in entries.upper():
                stringEntries.append(entries)
        return render(request, "encyclopedia/index.html", {
            "entries": stringEntries,
            "search": True,
            "data": data
        })
    else:
        return HttpResponseRedirect(reverse("wiki:get_title", kwargs={"title": data}))

def newPage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if (util.get_entry(title) is None):
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("wiki:get_title", kwargs={"title": title}))
            else:
                return render(request, "encyclopedia/newPage.html", {
                "form": form,
                "entry": title,
                "exist": True
                })
        else:
            return render(request, "encyclopedia/newPage.html", {
                "form": form,
                "exist": False                
            })
    else:
        return render(request, "encyclopedia/newPage.html", {
            "form": NewPageForm(),
            "exist": False
        })

def edit(request, title):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:get_title", kwargs={"title": title}))
    else:
        entry = util.get_entry(title)
        if entry is None:
            return render(request, "encyclopedia/404.html", {
                "entriesTitle": entry
            })
        else:
            form = NewPageForm()
            form.fields["title"].initial = title
            form.fields["content"].initial = entry
            return render(request, "encyclopedia/editPage.html", {
                "form": form,
                "entriesTitle": entry
            })

def random(request):
    entries = util.list_entries()
    entry = choice(entries)
    return HttpResponseRedirect(reverse("wiki:get_title", kwargs={"title": entry}))
    

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit encyclopedia
{% endblock %}

{% block body %}

    <h1>Edit a encyclopedia</h1>
    <div class="container mt-3">
        <form action="{{ entriesTitle }}/edit" method="POST">
            {% csrf_token %}
            {{ form }}
            <div>
                <button type="submit" class="btn btn-outline-primary btn-sm">Save</button>
            </div>
        </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entriesTitle }}
{% endblock %}

{% block body %}
    {{ entries|safe }}
    <a class="btn btn-outline-success btn-sm" href="{{ entriesTitle }}/edit" role="button">Edit</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {% if search %}
        <h1>Searching for: {{ data }}</h1> 
    {% else %}
        <h1>All Pages</h1>
    {% endif %}    

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New encyclopedia
{% endblock %}

{% block body %}
{% if exist %}
    <div class="alert alert-danger mt-2" role="alert">
        This <strong>{{ entry }}</strong> entry already exists. If you want to view or edit it, <a href="wiki/{{ entry }}">click here.</a>
    </div>
{% endif %}

    <h1>Create a new encyclopedia</h1>
    <div class="container mt-3">
        <form action="{% url 'wiki:newPage' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <div>
                <button type="submit" class="btn btn-outline-primary btn-sm">Save</button>
            </div>
        </form>
    </div>

{% endblock %}